version: '3.8'

services:
  # Serviço do PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: streaming-app-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: streaming_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Serviço do Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streaming-app-backend
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/streaming_app?schema=public"
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: sh -c "npx prisma migrate dev --name init && npx prisma db seed && npm run dev"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
